### ISSUE TITLE
Publish OkHttp3 4.1.1 and 4.2.2 to Nuget 

### ISSUE THREAD

**Issue by 4brunu** [mattleibow/square-bindings#57]
Hey,
Can you please publish 4.1.1 and 4.2.2 of OkHttp3 to the Nuget Gallery?
Because it only has version 4.0 published on https://www.nuget.org/packages/Square.OkHttp3/.
Thanks

**Comment by mattleibow** [comment]
Publishing now... Should be up in a bit.
