### ISSUE TITLE
Dependency to Xamarin.Jetbrains.Annotations ?

### ISSUE THREAD

**Issue by jonathanantoine** [mattleibow/square-bindings#60]
Hello,

Why does the latest version have a dependency to Xamarin.Jetbrains.Annotations ?

Regards

**Comment by mattleibow** [comment]
This is because the latest version of the Square libraries are built using Kotlin, and this is what all Kotlin apps use. It should have the annotations and the Kotlin stdlib. This also happens for all Java/Kotlin apps. If you add the square libraries, you get all the kotlin dependencies.
