### ISSUE TITLE
Please upgrade OkHttp3.UrlConnection

### ISSUE THREAD

**Issue by tranb3r** [mattleibow/square-bindings#62]
@Redth @mattleibow 
Now that you've released new versions of OkHttp3 (4.x) and Okio, could you please also publish a new version of OkHttp3.UrlConnection with bindings to the kotlin libs ? 
Thanks

**Comment by tranb3r** [comment]
@Redth @mattleibow 
Are you guys still maintaining these bindings ?

**Comment by tranb3r** [comment]
@Redth @mattleibow 
Guys, I don't want to rush you, since I remember that it took you 1 year to merge my PR last time... https://github.com/mattleibow/square-bindings/pull/21
But, I'd really like to know how long is too long to wait for ANY kind of answer from you.
Thanks.

**Comment by mattleibow** [comment]
This has now been moved to https://github.com/xamarin/XamarinComponents/tree/master/Android/SquareOkHttp3UrlConnection

I'll probably be moving the other platforms there too and then archive this repo.
